[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
